### ISSUE TITLE
BUG: Output is correct but incomplete

### ISSUE THREAD

**Issue by ndharari** [lucasvanmol/obsidian-latex-ocr#19]
Since today, when I run the plugin I get an incomplete reponse, as if the model run correctly but is just showing me X number of characters.

**Comment by lucasvanmol** [comment]
I'm seeing the same issue; I think the problem is with HuggingFace as using the inference API [on the website](https://huggingface.co/Norm/nougat-latex-base) isn't returning the full text either. Apparently there were some issues earlier today, this might still be a result of that: https://twitter.com/huggingface/status/1756401140495679871. Using the model locally still seems to work fine as an alternative.

**Comment by Gallium314** [comment]
I seem to be having the same problem, I get around 5 symbols and no more consistently. My issue started around three days ago as well, though I don't remember the exact timing.

**Comment by Nilati** [comment]
Same here too
